### ISSUE TITLE
List of small immediate changes for VESPERS

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#1068]
Users ran into some issues over the weekend and I need to look into fixing them.  

- [x] Line scans not displaying correctly.  This may have already been handled in #1066.  
- [x] I need to add a mechanism to export the spectra that are automatically saved.  Probably make a popup of some kind.
- [x] Get the crash reporter running on VESPERS.
- [x] There is a bug in the startup for the network synchronizer changes I made.  Apparently, the first time you try to restart the application, it'll think you're a first time user.  However, if you cancel it the first time dialog and run the application again it works as expected.
- [x] After restarting the application, ROIs are being reloaded, but when you run your first scan, it removes them all and your scan has nothing in them.
- [x] Need more strict pausing/resuming when beam goes down. Related:  #1089 
- [x] First point in line scan is incorrect.  This is likely the scaler, but it seemed to happen even if scans were 1.0 second. #1060
- There was apparently a long delay in starting scans (approximately 60 seconds).  My guess as of right now is that the user on Sunday started up the application but forgot to set that data should be stored locally.  I need to make sure that saving locally is automatically set.  

__Explanation__: Turns out that the extra delay is actually the computation of all the ROIs.  Which makes sense since it is going through all the data multiplied by 2048.  However, I doubt the amount of time actually spent.  Will need to investigate.  This is also just an added extra time, there still seems to be a problem when saving the initial file, which just seems to take longer using SL54.

__Further Explanation__:  This extra lag that is 60 seconds is actually on file write at the end of the scan.  As it turns out, there is an issue with the network that causes this delay.  Discussions with IT have yet to yield any solutions for this - particularly since there isn't a known way to reproduce the errors.
- [x] Need to add the ability change the min and max range for XRF detector views (#1038).

**Comment by dretrex** [comment]
Done in pull request #1174.  Took 15 minutes to do item 5 and 5 hours to do item 2.  The rest of them have time estimates in the issues they reference.
