### ISSUE TITLE
SGM Upgrade - Hexapod Driver

### ISSUE THREAD

**Issue by iainworkman** [acquaman/acquaman#1422]
This master issue was eventually split into 5 smaller issues, for better progress tracking and easier time estimation.

The issues can be found at:
#1460 
#1459 
#1458 
#1461 
#1462 

Edited June 23rd
Pull Request: #1442

**Comment by iainworkman** [comment]
There are a few notes about the application in its current (7da0c24) state:
- I had to remove mobility from the config file in acquamanCommon.pri as it seemed to be causing issued. Will look at returning this as we move closer to deploy.
- In order for this to build the PI_GCS2 drivers need to be located in ~/beamline/programming/acquaman/contrib/pi_gcs2/lib. Again, closer to deploy this will be brought closer to the standard AM way of including libraries.
- The build requires glibc v2.7 which is not available on SL5.4. We can get access to a virtual opi running SL7.1 for building. For those not using SL5.4 this shouldn't be an issue.

**Comment by dretrex** [comment]
Hey @iainworkman, would you mind if I made this a pull request so that it makes code review a little easier?

**Comment by iainworkman** [comment]
Sure, was going to do that, but it slipped my mind.

**Comment by iainworkman** [comment]
Commands still left to do:
- [ ] Move relative
- [ ] Set low position soft limit
- [ ] Get low position soft limit
- [ ] Get on target state
- [ ] Set high position soft limit
- [ ] Get high position soft limit
- [ ] Get position units
- [ ] Set cycle time
- [ ] Get cycle time
- [ ] Set pivot point
- [ ] Get pivot point
- [ ] Set servo mode
- [ ] Get servo mode
- [ ] Get min commandable position
- [ ] Get max commandable position
- [ ] Get number of record tables
- [ ] Set closed loop velocity
- [ ] Get closed loop velocity
- [ ] Set system velocity
- [ ] Get system velocity
- [ ] Virtual move

**Comment by dretrex** [comment]
Since this was split into a bunch of more manageable issues, I'm going to close this one out.
