### ISSUE TITLE
IDEAS: Upgrade bugs and cleanup

### ISSUE THREAD

**Issue by epengr** [acquaman/acquaman#2059]
One issue to take care of a few little things that have cropped up after bringing IDEAS back up to Master branch:

- [x] AMExtendedControlEditors on IDEASPersistentView all allow only '-1' as input (done in #2060)
- [x] AMExtendedControlEditors on Sample alignment all allow only '-1' as input, except vacuum stage only allows 150 (done in #2060)
- [x]  Mono settling time needs tweaking to resolve stutter/noise for 1s dwell XANES
- [x] Not convinced that AM1DCalibrationAB is properly saving all properties (moved to #2256)
- [x] Generic scan needs cleanup actions
- [x] Transmission and reference checkboxes should be independent
- [x] EXAFS energy range label shows k values for end point (with eV as units)
- [x] Scaler not resetting properly after XANES scans. It's entering continuous mode, but the dwell time is not changed.
- [x] Scaler dwell for continuous mode needs to be 250 ms, not 100 ms - IOC is having issues with that speed
- [x] Default XANES region sets near edge too short
- [x] First point of (KETEK!) dwell time channel in XANES scans is the previous dwell time setting
- [x] "Beam is on!"/"Beam is off!" label on persistent view not responding - signal not generated? (Moved to #2110)
- [x] The scan select dialog presented when "Export Scan" from the KETEK panel is not populated, the filter has to be cleared for scans to appear (filter values need to be fixed, I assume) (Moved to #2106)
- [x] The peaking time drop box on the KETEK panel is not labelled.
- [x] XRF acquisition status on sidebar
- [x] Turn off higher order datasets for default export
- [x] XRF detector status in sidebar

**Comment by dretrex** [comment]
For the generic scan needs cleanup actions, see #2055 and maybe have a chat with @helfrij.

**Comment by helfrij** [comment]
Hey @epengr, I'm in the BioXAS main users area today if you want to chat.

**Comment by epengr** [comment]
I think I'm on to something or the -1's.  My beamline energy control is reporting

canMove()=  false

so the AMExtendedControlEditor is setting itself read only.

**Comment by epengr** [comment]
`canWrite()` comes down to `isConnected() && ca_write_access(chid_)`, and `isConnected() `is reporting false at the time the control is created.

**Comment by helfrij** [comment]
The problem I'm seeing with the '-1s' seems to be more related to the control minimum and maximum values. When I ask a control for it's minimum and maximum values in a QDebug after startup, I think it reports the values correctly, but the editor's minimum and maximum never appears to be updated (they're both -1 by default).

I can fix my problem by adding connect statements to the control editor to listen for updates to the control's minimum and maximum values, and forcing an update.

**Comment by helfrij** [comment]
Hey @epengr, my solution to the '-1' control editor problem is in #2061. Would you be interested in testing this branch out to see if it fixes your problems?

**Comment by epengr** [comment]
Yes, that fixed it.  Thanks!

**Comment by helfrij** [comment]
That's interesting. I guess this would solve that problem if the defaults for that motor's minimum and maximum values were 150?

**Comment by epengr** [comment]
The motorGroupView had setMotorValuesRange(-10, 150). I didn't get a chance to look any further...

**Comment by helfrij** [comment]
Hey @epengr. The changes in #2057 have been merged into master, which would allow for the commissioning tool to have beamline-specific initialization and cleanup actions. Come find me if you want to talk about implementing this for IDEAS.

**Comment by epengr** [comment]
Time Estimate: 1.5 days
