### ISSUE TITLE
Releasing VESPERS

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#860]
I'm going to use this issue for consolidated issues for releasing a new version of AM for VESPERS.
- [x] ROI sources are not auto selected for 2D maps
- [x] Make sure that the proper ROI is auto-selected for XAS and line scans.
- [x] Switch ion chambers to start on voltage rather than counts.
- [x] Finish XRF scan controller as #797 
- [x] Make estimated times better for single and 4 element vortex's
- [x] Make sure all visual cues for bad regions is properly fixed. (2D and spatial)
- [x] Basic test that 3D scan controllers work. #615 
- [x] Make sure beam dump detection and pausing works. #660 
- [x] Pilatus aurora size updates properly in Pilatus view.
- [x] MPlot and AM optimizations that don't cripple scan progression #868 
- [x] Detector dwell times don't seem to be pushed to the detector. #915 
- [x] Incorporate the big beam stages to scan configurations.  Can't just cherry-pick the commit since it involved classes that don't exist anymore. #899 
- [x] Incorporate the wire stage into the spatial scan. #912 
- [x] Add the wire stage pseudo control reset to the application. #904
