### ISSUE TITLE
Add big beam stages to new VESPERS application

### ISSUE THREAD

**Issue by dretrex** [acquaman/acquaman#899]
I added in two new motors to the old user interface but that commit can't just be added to the new version since it contains classes that don't exist anymore.  I need to add it into the latest version in #860.
- [x] Add to X and Z to enum in VESPERS.h
- [x] Add X and Z to the configuration view.
- [x] Add to the scan controller any aspects that are required for new motors.
- [x] Make sure that the otherPostion and normalPositions are updated appropriately. (Remember, no normal motor for these stages.)
- [x] Add to the convenience methods inside VESPERSAppController about auto-selection when motor group objects change.
